# Generated by Django 5.2.11 on 2026-02-26 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_id", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, verbose_name="Oyuncu Adı")),
                (
                    "current_team",
                    models.CharField(max_length=100, verbose_name="Takım"),
                ),
                ("position", models.CharField(max_length=30, verbose_name="Mevki")),
                ("turnovers", models.FloatField(default=0.0, verbose_name="Top Kaybı")),
                (
                    "field_goals_missed",
                    models.FloatField(default=0.0, verbose_name="Kaçan Şut"),
                ),
                (
                    "free_throws_missed",
                    models.FloatField(default=0.0, verbose_name="Kaçan Serbest Atış"),
                ),
                ("points", models.FloatField(default=0.0, verbose_name="Sayı")),
                ("rebounds", models.FloatField(default=0.0, verbose_name="Ribaund")),
                ("assists", models.FloatField(default=0.0, verbose_name="Asist")),
                (
                    "three_pts",
                    models.FloatField(default=0.0, verbose_name="3 Sayılık Basket"),
                ),
                ("steals", models.FloatField(default=0.0, verbose_name="Top Çalma")),
                ("blocks", models.FloatField(default=0.0, verbose_name="Blok")),
            ],
        ),
        migrations.CreateModel(
            name="UserTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(max_length=100, verbose_name="Fantasy Takım Adı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "players",
                    models.ManyToManyField(
                        blank=True, to="league.player", verbose_name="Oyuncular"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
        ),
    ]
