# Generated by Django 3.2.5 on 2026-02-24 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Oyuncu Adı')),
                ('team', models.CharField(max_length=100, verbose_name='Takım')),
                ('position', models.CharField(choices=[('PG', 'Point Guard'), ('SG', 'Shooting Guard'), ('SF', 'Small Forward'), ('PF', 'Power Forward'), ('C', 'Center')], max_length=2, verbose_name='Mevki')),
                ('turnovers', models.IntegerField(default=0, verbose_name='Top Kaybı')),
                ('personal_fouls', models.IntegerField(default=0, verbose_name='Kişisel Faul')),
                ('field_goals_missed', models.IntegerField(default=0, verbose_name='Kaçan Şut')),
                ('free_throws_missed', models.IntegerField(default=0, verbose_name='Kaçan Serbest Atış')),
                ('points', models.IntegerField(default=0, verbose_name='Sayı')),
                ('rebounds', models.IntegerField(default=0, verbose_name='Ribaund')),
                ('assists', models.IntegerField(default=0, verbose_name='Asist')),
                ('three_pts', models.IntegerField(default=0, verbose_name='3 Sayılık Basket')),
                ('steals', models.IntegerField(default=0, verbose_name='Top Çalma')),
                ('blocks', models.IntegerField(default=0, verbose_name='Blok')),
            ],
        ),
    ]
