# Generated by Django 3.2.5 on 2026-02-21 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(blank=True, null=True, unique=True, verbose_name='API ID')),
                ('name', models.CharField(max_length=100, verbose_name='Oyuncu Adı')),
                ('team', models.CharField(max_length=100, verbose_name='Takım')),
                ('position', models.CharField(choices=[('KL', 'Kaleci'), ('DF', 'Defans'), ('OS', 'Orta Saha'), ('FV', 'Forvet')], max_length=2, verbose_name='Mevki')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('yellow_cards', models.IntegerField(default=0, verbose_name='Sarı Kart')),
                ('red_cards', models.IntegerField(default=0, verbose_name='Kırmızı Kart')),
                ('own_goals', models.IntegerField(default=0, verbose_name='Kendi Kalesine Gol')),
                ('missed_penalties', models.IntegerField(default=0, verbose_name='Kaçan Penaltı')),
                ('errors_leading_to_goal', models.IntegerField(default=0, verbose_name='Gole Sebep Olan Hata')),
                ('clean_sheets', models.IntegerField(default=0, verbose_name='Gol yememe')),
            ],
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, verbose_name='Fantasy Takım Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(to='league.Player', verbose_name='Kadrodaki Oyuncular')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
        ),
    ]
